<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<!-- Generated by {%COWIKI_FULL_NAME%} ({%COWIKI_HOME%}) -->

<html>
<head>
<title>{%PAGE_TITLE%}</title>

<meta name="generator" content="{%COWIKI_FULL_NAME%}, {%COWIKI_HOME%}">
<meta name="robots" content="{%META_ROBOT_INDEX%}">
<meta name="keywords" content="{%META_KEYWORDS%}">
<meta name="mssmarttagspreventparsing" content="true">
<meta name="revisit-after" content="{%DOCUMENT_REVISIT_AFTER%} days">
<meta http-equiv="content-type" content="text/html; charset={%I18N_CHARSET%}">

<base href="{%COWIKI_BASE_HREF%}">

<style type="text/css" media="screen">
<!--

  a {
    color: {%COLOR_LINK%};
  }

  a:active {
    color: {%COLOR_ALINK%};
  }

  a:visited {
    color: {%COLOR_VLINK%};
  }

  p, ol, ul, li, dl, dt, dd, blockquote {
    color: {%COLOR_TEXT%};
  }

  td, th, span {
    color: {%COLOR_TEXT%};
    font-weight: 500;
  }

  blockquote {
    margin-right: 0px;
  }

  h1, h2, h3, h4, h5, h6  {
    color: {%COLOR_TEXT%};
    font-weight:500;
    margin-top:8px;
  }

  pre, tt {
    font-family: monospace;
    color: {%COLOR_TEXT%};
  }

  pre.code {
    padding: 5px;
    border-style: solid;
    border-width: 1px;
    border-color: #CCCCCC;
    background-color: #F4F4F4;
  }

  hr  {
    width: 100%;
    height: 1px;
    background-color: #CCCCCC;
    border-width: 0px;
    padding: 0px;
    color: #CCCCCC;
  }

  /* ------------------------------------------------------------------*/

  .tuborgbox {
    border-style: solid;
    border-width: 1px;
    border-top-color: {%COLOR_TUBORG_HIGHLIGHT%};
    border-left-color: {%COLOR_TUBORG_HIGHLIGHT%};
    border-right-color: {%COLOR_TUBORG_SHADOW%};
    border-bottom-color: {%COLOR_TUBORG_SHADOW%};
  }

  .tuborgboxsimple {
    border-style: solid;
    border-width: 1px;
    border-color: {%COLOR_TUBORG_SHADOW%};
  }

  .rappsbox {
    border-style: solid;
    border-width: 1px;
    border-top-color: {%COLOR_RAPPS_HIGHLIGHT%};
    border-left-color: {%COLOR_RAPPS_HIGHLIGHT%};
    border-right-color: {%COLOR_RAPPS_SHADOW%};
    border-bottom-color: {%COLOR_RAPPS_SHADOW%};
  }

  .rappsboxsimple {
    border-style: solid;
    border-width: 1px;
    border-color: {%COLOR_RAPPS_SHADOW%};
  }

  .linklist {
    font-size: 92%;
  }

  .monospace {
    font-family: monospace;
    font-size:92%;
  }

  .tiny {
    font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif;
    font-size: 11px;
  }

  .small {
    font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif;
    font-size: 12px;
  }

  .medium {
    font-family: Verdana, Tahoma, Arial, Helvetica, sans-serif;
    font-size: 13px;
  }

-->
</style>

<script language="JavaScript" type="text/javascript">
<!--

  window.onerror = null;
  var undefined;

  // These function skeletons will help to avoid client script errors if
  // a plugin is going to use them in its output. This is for the printer
  // friendly output, of course.

  function fireClickEvent() {}
  function fireClickEventOnChild() {}
  function mover() {}
  function mout() {}
  function moverOnParentName() {}
  function moutOnParentName() {}
  function moverOnPrevSiblingName() {}
  function moutOnPrevSiblingName() {}
  function moverOnNextSiblingName() {}
  function moutOnNextSiblingName() {}

//-->
</script>

</head>
